// import { ClientReasons } from '../_api';
import { getSelectOptions } from '../lib/helper';

export enum ClientStatus {
  All = 'All',
  Active = 'Active',
  Inactive = 'Inactive',
  Invited = 'Invited',
  Deactivated = 'Deactivated',
}

export enum USStateEnum {
  Alabama = 'AL',
  Alaska = 'AK',
  Arizona = 'AZ',
  Arkansas = 'AR',
  California = 'CA',
  Colorado = 'CO',
  Connecticut = 'CT',
  Delaware = 'DE',
  Florida = 'FL',
  Georgia = 'GA',
  Hawaii = 'HI',
  Idaho = 'ID',
  Illinois = 'IL',
  Indiana = 'IN',
  Iowa = 'IA',
  Kansas = 'KS',
  Kentucky = 'KY',
  Louisiana = 'LA',
  Maine = 'ME',
  Maryland = 'MD',
  Massachusetts = 'MA',
  Michigan = 'MI',
  Minnesota = 'MN',
  Mississippi = 'MS',
  Missouri = 'MO',
  Montana = 'MT',
  Nebraska = 'NE',
  Nevada = 'NV',
  NewHampshire = 'NH',
  NewJersey = 'NJ',
  NewMexico = 'NM',
  NewYork = 'NY',
  NorthCarolina = 'NC',
  NorthDakota = 'ND',
  Ohio = 'OH',
  Oklahoma = 'OK',
  Oregon = 'OR',
  Pennsylvania = 'PA',
  RhodeIsland = 'RI',
  SouthCarolina = 'SC',
  SouthDakota = 'SD',
  Tennessee = 'TN',
  Texas = 'TX',
  Utah = 'UT',
  Vermont = 'VT',
  Virginia = 'VA',
  Washington = 'WA',
  WestVirginia = 'WV',
  Wisconsin = 'WI',
  Wyoming = 'WY',
}

export const UsStateToText = {
  [USStateEnum.Alabama]: 'Alabama',
  [USStateEnum.Alaska]: 'Alaska',
  [USStateEnum.Arkansas]: 'Arkansas',
  [USStateEnum.Arizona]: 'Arizona',
  [USStateEnum.California]: 'California',
  [USStateEnum.Colorado]: 'Colorado',
  [USStateEnum.Connecticut]: 'Connecticut',
  [USStateEnum.Delaware]: 'Delaware',
  [USStateEnum.Florida]: 'Florida',
  [USStateEnum.Georgia]: 'Georgia',
  [USStateEnum.Hawaii]: 'Hawaii',
  [USStateEnum.Idaho]: 'Idaho',
  [USStateEnum.Illinois]: 'Illinois',
  [USStateEnum.Indiana]: 'Indiana',
  [USStateEnum.Iowa]: 'Iowa',
  [USStateEnum.Kansas]: 'Kansas',
  [USStateEnum.Kentucky]: 'Kentucky',
  [USStateEnum.Louisiana]: 'Louisiana',
  [USStateEnum.Maine]: 'Maine',
  [USStateEnum.Maryland]: 'Maryland',
  [USStateEnum.Massachusetts]: 'Massachusetts',
  [USStateEnum.Michigan]: 'Michigan',
  [USStateEnum.Minnesota]: 'Minnesota',
  [USStateEnum.Mississippi]: 'Mississippi',
  [USStateEnum.Missouri]: 'Missouri',
  [USStateEnum.Montana]: 'Montana',
  [USStateEnum.Nebraska]: 'Nebraska',
  [USStateEnum.Nevada]: 'Nevada',
  [USStateEnum.NewHampshire]: 'New Hampshire',
  [USStateEnum.NewJersey]: 'New Jersey',
  [USStateEnum.NewMexico]: 'New Mexico',
  [USStateEnum.NewYork]: 'New York',
  [USStateEnum.NorthCarolina]: 'North Carolina',
  [USStateEnum.NorthDakota]: 'North Dakota',
  [USStateEnum.Ohio]: 'Ohio',
  [USStateEnum.Oklahoma]: 'Oklahoma',
  [USStateEnum.Oregon]: 'Oregon',
  [USStateEnum.Pennsylvania]: 'Pennsylvania',
  [USStateEnum.RhodeIsland]: 'Rhode Island',
  [USStateEnum.SouthCarolina]: 'South Carolina',
  [USStateEnum.SouthDakota]: 'South Dakota',
  [USStateEnum.Tennessee]: 'Tennessee',
  [USStateEnum.Texas]: 'Texas',
  [USStateEnum.Utah]: 'Utah',
  [USStateEnum.Vermont]: 'Vermont',
  [USStateEnum.Virginia]: 'Virginia',
  [USStateEnum.Washington]: 'Washington',
  [USStateEnum.WestVirginia]: 'West Virginia',
  [USStateEnum.Wisconsin]: 'Wisconsin',
  [USStateEnum.Wyoming]: 'Wyoming',
};

export const UsStateOptions = getSelectOptions(UsStateToText);

export enum ListStatus {
  All = 'All',
  Active = 'Active',
  Inactive = 'Inactive',
  Invited = 'Invited',
}

export enum TherapistListStatus {
  All = 'All',
  Active = 'Active',
  Inactive = 'Inactive',
  Invited = 'Invited',
  Deactivated = 'Deactivated',
}

// export const ClientReasonToName: Record<ClientReasons, string> = {
//   [ClientReasons.CourtOrdered]: 'Court Ordered',
//   [ClientReasons.Voluntary]: 'Voluntary',
// };
// export const clientReasonOptions = getSelectOptions(ClientReasonToName);
