/**
 * Format number as Indian Rupee currency
 */
const formatCurrency = (amount: number): string => {
  return `₹${amount.toLocaleString("en-IN")}`;
};

/**
 * Export dashboard data to Excel
 */
export const exportDashboardToExcel = async (
  financialData: {
    totalAmountSpentThisYear: number;
    amountSpentForSchoolStudents: number;
    amountSpentForCollegeStudents: number;
    amountSpentForResearchScholars: number;
    amountSpentForMedicalAssistance: number;
  },
  applicationMetrics: {
    totalApplications: number;
    submitted: number;
    approved: number;
    underReview: number;
  },
  recentApplications: {
    applicationNo: string;
    studentName: string;
    classStudying: string;
    courseStream?: string;
    institutionName: string;
    mobileNumber?: string;
    status: string;
    scholarshipId: string;
  }[],
  academicYear: string,
  userName: string,
): Promise<void> => {
  try {
    // Dynamic import to handle cases where package might not be installed
    // Using variable to make import truly dynamic and avoid Vite static analysis
    const moduleName = "xlsx";
    // @ts-expect-error - xlsx package may not be installed, Vite will try to resolve it
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    const xlsxModule = await import(/* @vite-ignore */ moduleName);
    // Handle both default and namespace exports
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
    const XLSX = (xlsxModule.default ?? xlsxModule) as any;
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    const workbook = XLSX.utils.book_new();

  // Financial Summary Sheet
  const financialSheetData = [
    ["Financial Summary", ""],
    ["", ""],
    ["Total Amount Spent This Year", formatCurrency(financialData.totalAmountSpentThisYear)],
    ["Amount Spent for School Students", formatCurrency(financialData.amountSpentForSchoolStudents)],
    ["Amount Spent for College Students", formatCurrency(financialData.amountSpentForCollegeStudents)],
    ["Amount Spent for Research Scholars", formatCurrency(financialData.amountSpentForResearchScholars)],
    ["Amount Spent for Medical Assistance", formatCurrency(financialData.amountSpentForMedicalAssistance)],
  ];
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    const financialSheet = XLSX.utils.aoa_to_sheet(financialSheetData);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    XLSX.utils.book_append_sheet(workbook, financialSheet, "Financial Summary");

  // Application Analytics Sheet
  const analyticsSheetData = [
    ["Application Analytics", ""],
    ["", ""],
    ["Total Applications", applicationMetrics.totalApplications],
    ["Submitted", applicationMetrics.submitted],
    ["Approved", applicationMetrics.approved],
    ["Under Review", applicationMetrics.underReview],
  ];
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    const analyticsSheet = XLSX.utils.aoa_to_sheet(analyticsSheetData);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    XLSX.utils.book_append_sheet(workbook, analyticsSheet, "Application Analytics");

  // Recent Applications Sheet
  const applicationsSheetData = [
    ["Application No", "Student Name", "Class Studying", "Course/Stream", "Institution Name", "Mobile Number", "Status", "Scholarship ID"],
    ...recentApplications.map((app) => [
      app.applicationNo,
      app.studentName,
      app.classStudying,
      app.courseStream ?? "",
      app.institutionName,
      app.mobileNumber ?? "",
      app.status,
      app.scholarshipId,
    ]),
  ];
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    const applicationsSheet = XLSX.utils.aoa_to_sheet(applicationsSheetData);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    XLSX.utils.book_append_sheet(workbook, applicationsSheet, "Recent Applications");

  // Metadata Sheet
  const metadataSheetData = [
    ["Dashboard Export Information", ""],
    ["", ""],
    ["Academic Year", academicYear],
    ["Generated By", userName],
    ["Generated On", new Date().toLocaleString("en-IN")],
  ];
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    const metadataSheet = XLSX.utils.aoa_to_sheet(metadataSheetData);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    XLSX.utils.book_append_sheet(workbook, metadataSheet, "Metadata");

    // Generate filename
    const filename = `Dashboard_Export_${academicYear}_${new Date().toISOString().split("T")[0]}.xlsx`;

    // Write file
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    XLSX.writeFile(workbook, filename);
  } catch (error) {
    console.error("Error exporting to Excel. Please ensure 'xlsx' package is installed:", error);
    throw new Error("Excel export failed. Please install the 'xlsx' package: npm install xlsx");
  }
};

/**
 * Export dashboard data to Word
 */
export const exportDashboardToWord = async (
  financialData: {
    totalAmountSpentThisYear: number;
    amountSpentForSchoolStudents: number;
    amountSpentForCollegeStudents: number;
    amountSpentForResearchScholars: number;
    amountSpentForMedicalAssistance: number;
  },
  applicationMetrics: {
    totalApplications: number;
    submitted: number;
    approved: number;
    underReview: number;
  },
  recentApplications: {
    applicationNo: string;
    studentName: string;
    classStudying: string;
    courseStream?: string;
    institutionName: string;
    mobileNumber?: string;
    status: string;
    scholarshipId: string;
  }[],
  academicYear: string,
  userName: string,
): Promise<void> => {
  try {
    // Dynamic import to handle cases where package might not be installed
    // Using variable to make import truly dynamic and avoid Vite static analysis
    const moduleName = "docx";
    // @ts-expect-error - docx package may not be installed, Vite will try to resolve it
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    const docxModule = await import(/* @vite-ignore */ moduleName);
    // Handle both default and named exports
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
    const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, AlignmentType } = docxModule as any;
    
    const doc = new Document({
    sections: [
      {
        children: [
          // Title
          new Paragraph({
            text: "Dashboard Export Report",
            heading: "Heading1",
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),

          // Metadata
          new Paragraph({
            children: [
              new TextRun({ text: "Academic Year: ", bold: true }),
              new TextRun({ text: academicYear }),
            ],
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Generated By: ", bold: true }),
              new TextRun({ text: userName }),
            ],
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Generated On: ", bold: true }),
              new TextRun({ text: new Date().toLocaleString("en-IN") }),
            ],
            spacing: { after: 400 },
          }),

          // Financial Summary Section
          new Paragraph({
            text: "Financial Summary",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Category")] }),
                  new TableCell({ children: [new Paragraph("Amount")] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Total Amount Spent This Year")] }),
                  new TableCell({ children: [new Paragraph(formatCurrency(financialData.totalAmountSpentThisYear))] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Amount Spent for School Students")] }),
                  new TableCell({ children: [new Paragraph(formatCurrency(financialData.amountSpentForSchoolStudents))] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Amount Spent for College Students")] }),
                  new TableCell({ children: [new Paragraph(formatCurrency(financialData.amountSpentForCollegeStudents))] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Amount Spent for Research Scholars")] }),
                  new TableCell({ children: [new Paragraph(formatCurrency(financialData.amountSpentForResearchScholars))] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Amount Spent for Medical Assistance")] }),
                  new TableCell({ children: [new Paragraph(formatCurrency(financialData.amountSpentForMedicalAssistance))] }),
                ],
              }),
            ],
          }),

          // Application Analytics Section
          new Paragraph({
            text: "Application Analytics",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Metric")] }),
                  new TableCell({ children: [new Paragraph("Count")] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Total Applications")] }),
                  new TableCell({ children: [new Paragraph(applicationMetrics.totalApplications.toString())] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Submitted")] }),
                  new TableCell({ children: [new Paragraph(applicationMetrics.submitted.toString())] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Approved")] }),
                  new TableCell({ children: [new Paragraph(applicationMetrics.approved.toString())] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Under Review")] }),
                  new TableCell({ children: [new Paragraph(applicationMetrics.underReview.toString())] }),
                ],
              }),
            ],
          }),

          // Recent Applications Section
          new Paragraph({
            text: "Recent Applications",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              // Header row
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Application No")] }),
                  new TableCell({ children: [new Paragraph("Student Name")] }),
                  new TableCell({ children: [new Paragraph("Class Studying")] }),
                  new TableCell({ children: [new Paragraph("Institution Name")] }),
                  new TableCell({ children: [new Paragraph("Status")] }),
                  new TableCell({ children: [new Paragraph("Scholarship ID")] }),
                ],
              }),
              // Data rows
              ...recentApplications.map(
                (app) =>
                  new TableRow({
                    children: [
                      new TableCell({ children: [new Paragraph(app.applicationNo)] }),
                      new TableCell({ children: [new Paragraph(app.studentName)] }),
                      new TableCell({ children: [new Paragraph(app.classStudying)] }),
                      new TableCell({ children: [new Paragraph(app.institutionName)] }),
                      new TableCell({ children: [new Paragraph(app.status)] }),
                      new TableCell({ children: [new Paragraph(app.scholarshipId)] }),
                    ],
                  }),
              ),
            ],
          }),
        ],
      },
    ],
  });

    // Generate the document
    const blob = await Packer.toBlob(doc);

    // Download the file
    const filename = `Dashboard_Export_${academicYear}_${new Date().toISOString().split("T")[0]}.docx`;
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Error exporting to Word. Please ensure 'docx' package is installed:", error);
    throw new Error("Word export failed. Please install the 'docx' package: npm install docx");
  }
};

