import { ScholarshipReportData } from "./types";

// Mock data for demonstration - replace with actual API calls
export const mockScholarshipData: ScholarshipReportData[] = [
  {
    applicationNo: "AF2510001",
    aadhaarId: "375470648340",
    studentName: "Kavipriya",
    studentId: "SEC21CB033",
    classStudying: "BE Computer Science",
    institutionName: "Sai Ram Institute",
    fatherName: "Kumar",
    fatherOfficeName: "TCS",
    motherName: "Lakshmi",
    motherOfficeName: "-",
    guardianName: "-",
    guardianOfficeName: "-",
    gender: "Female",
    checkInFavor: "Sai Ram Institute",
    approvedAmount: "50000",
    issuedAmount: "50000",
    scholarshipId: "SCH25001",
    ddCheckNo: "DD987654",
    donateDate: "20/06/2025",
    bankName: "HDFC Bank",
    appliedDate: "15/05/2025",
    scholarshipYear: "2024-2025",
    scholarshipFor: "Tuition Fee",
    status: "Approved",
  },
  {
    applicationNo: "AF2510002",
    aadhaarId: "482736159204",
    studentName: "Malathi",
    studentId: "SEC21CB034",
    classStudying: "BE IT",
    institutionName: "Sai Ram Institute",
    fatherName: "Ravi",
    fatherOfficeName: "Infosys",
    motherName: "Sita",
    motherOfficeName: "School",
    guardianName: "-",
    guardianOfficeName: "-",
    gender: "Female",
    checkInFavor: "Sai Ram Institute",
    approvedAmount: "45000",
    issuedAmount: "45000",
    scholarshipId: "SCH25002",
    ddCheckNo: "DD987655",
    donateDate: "21/06/2025",
    bankName: "SBI",
    appliedDate: "16/05/2025",
    scholarshipYear: "2024-2025",
    scholarshipFor: "Tuition Fee",
    status: "Approved",
  },
  {
    applicationNo: "AF2510003",
    aadhaarId: "593847260315",
    studentName: "Ananya",
    studentId: "SEC21CB035",
    classStudying: "B.Tech",
    institutionName: "Sai Ram Institute",
    fatherName: "Suresh",
    fatherOfficeName: "Self Employed",
    motherName: "Gita",
    motherOfficeName: "-",
    guardianName: "-",
    guardianOfficeName: "-",
    gender: "Female",
    checkInFavor: "Sai Ram Institute",
    approvedAmount: "55000",
    issuedAmount: "55000",
    scholarshipId: "SCH25003",
    ddCheckNo: "DD987656",
    donateDate: "22/06/2025",
    bankName: "Axis Bank",
    appliedDate: "17/05/2025",
    scholarshipYear: "2024-2025",
    scholarshipFor: "Hostel Fee",
    status: "Completed",
  },
  {
    applicationNo: "AF2510004",
    aadhaarId: "674829301456",
    studentName: "Kavya",
    studentId: "SEC21CB036",
    classStudying: "12th",
    institutionName: "Sai Ram School",
    fatherName: "Murugan",
    fatherOfficeName: "Driver",
    motherName: "Valli",
    motherOfficeName: "-",
    guardianName: "-",
    guardianOfficeName: "-",
    gender: "Female",
    checkInFavor: "Sai Ram School",
    approvedAmount: "25000",
    issuedAmount: "25000",
    scholarshipId: "SCH25004",
    ddCheckNo: "DD987657",
    donateDate: "23/06/2025",
    bankName: "ICICI Bank",
    appliedDate: "18/05/2025",
    scholarshipYear: "2024-2025",
    scholarshipFor: "School Fee",
    status: "Waiting",
  },
  {
    applicationNo: "AF2510005",
    aadhaarId: "785920413567",
    studentName: "Meera",
    studentId: "SEC21CB037",
    classStudying: "SSLC",
    institutionName: "Govt. School",
    fatherName: "Karthik",
    fatherOfficeName: "-",
    motherName: "Revathy",
    motherOfficeName: "Nurse",
    guardianName: "-",
    guardianOfficeName: "-",
    gender: "Female",
    checkInFavor: "Meera",
    approvedAmount: "10000",
    issuedAmount: "0",
    scholarshipId: "-",
    ddCheckNo: "-",
    donateDate: "-",
    bankName: "-",
    appliedDate: "19/05/2025",
    scholarshipYear: "2024-2025",
    scholarshipFor: "Books",
    status: "Registered",
  },
];

export const academicYearOptions = [
  { value: "2024-2025", label: "2024-2025" },
  { value: "2023-2024", label: "2023-2024" },
  { value: "2022-2023", label: "2022-2023" },
  { value: "2021-2022", label: "2021-2022" },
];

export const genderOptions = [
  { value: "all", label: "All Gender" },
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
];

export const statusOptions = [
  { value: "all", label: "All" },
  { value: "approved", label: "Approved" },
  { value: "completed", label: "Completed" },
  { value: "registered", label: "Registered" },
  { value: "rejected", label: "Rejected" },
  { value: "waiting", label: "Waiting" },
];

export const issuedTypeOptions = [
  { value: "all", label: "All" },
  { value: "individual", label: "Individual" },
  { value: "institution", label: "Institution" },
  { value: "concession", label: "Concession" },
];

